import "@/app/globals.css";
import { AdminDashboardHome } from "@/components/component/admin-dashboard-home";
import AdminSidebar from "@/components/shared/AdminSidebar";
import {
  Package2Icon,
  PackageIcon,
  SettingsIcon,
  ShoppingCartIcon,
  UsersIcon,
} from "lucide-react";
import Link from "next/link";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="grid min-h-screen w-full lg:grid-cols-[280px_1fr]">
          <AdminSidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
